
services:
  task-prize-api:
    build: ./TaskPrizeAPI
    ports:
      - "8080:8080"
    volumes:
      - ./TaskPrizeAPI:/app  # Mapeia o código local para o container
      - /app/target  # Ignora a pasta de build
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/task_prize_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - database
    networks:
      - app-network

  #task-prize-client:
  #  build: ./TaskPrizeClient
  #  ports:
  #    - "8081:8081"
  #  volumes:
  #    - ./TaskPrizeClient:/app  # Mapear o código local para dentro do container
  #    - /app/node_modules  # Ignorar node_modules para evitar conflito
  #  environment:
  #    - CHOKIDAR_USEPOLLING=true  # Necessário para que o hot-reload funcione no Docker
  #  depends_on:
  #    - task-prize-api
   # networks:
   #   - app-network
  task-prize-client-angular:
    build: ./TaskPrizeClient-Angular
    ports:
      - "8100:8100"
    volumes:
      - ./TaskPrizeClient-Angular:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - task-prize-api
    networks:
      - app-network
  database:
    image: postgres:15.0
    environment:
      POSTGRES_DB: task_prize_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
